### ISSUE TITLE
To  get some new high resolution method

### ISSUE THREAD

**Issue by wt20097019** [AlessandraGalli/PPG#1]
hello,
in your paper ,you use "**zero-padded to extend DFT vector length to 8192 samples**" to  get high resolution in spectrum, but sometimes it may cause cause problems .And you have mentioned that "Since the spectrum of PPG signals is mostly made up of harmonic components, this should not cause problems, their separation being usually good enough to resolve them". Considering that, the CZT  or Zoom-FFT can be used to decrease the operations. Have you try it? if  you haven't, i will try to do it and can show the result if you want.
sorry for my poor English.

**Comment by AlessandraGalli** [comment]
Hi, 
we chose zero-padding instead CZT and Zoom-FFT because the two methods that you propose have high computational cost. Of course we are happy of your interest about this problem, and we'll read carefully your code. If you write me your e-mail we can keep in touch. 
Thank you. 
Alessandra

**Comment by wt20097019** [comment]
Hi,
It's glad to hear from you. my e-mail is 20097019@cqu.edu.cn.
I have already try to use the 256-CZT for 0.5-4.5HZ instead zero-padding in you code . Most of them are basically the same with your results. In my opinion, the cost of 256-CZT is  2-3 times of 256-FFT，which may be less compared to the 8092- FFT.
But there are still some errors compared to the ECG. I will try to solve these errors in next days, then i can give you the right code.

The figure shows the difference of the CZT and FFT for one of the 12 datasets

![_20171219154450](https://user-images.githubusercontent.com/23414693/34146119-afd7ecf8-e4d3-11e7-9ae0-637e80d3920b.png)


Hope to keep in touch.
wangtao
