### ISSUE TITLE
Can you tell me how to get the results of the test set?

### ISSUE THREAD

**Issue by anyujh** [AlessandraGalli/PPG#3]
Can you tell me how to get the results of the test set?
The original web page has become invalid（ http://www.signalprocessingsociety.org/spcup2015/ )
thank you！

**Comment by anyujh** [comment]
I get it!

**Comment by marcellosicbaldi** [comment]
Hi @anyujh, can you tell me how did you do it? Thanks :)

**Comment by anyujh** [comment]
@marcellosicbaldi 
https://github.com/andtem2000/PPG
